# Generated by Django 4.2.9 on 2025-06-03 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dance_styles', '0008_update_event_prices'),
        ('dance_styles', '0010_video_videocomment_videoprogress'),
    ]

    operations = [
    ]
