# Generated by Django 5.1.6 on 2025-06-05 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dance_styles', '0011_merge_20250603_1228'),
        ('dance_styles', '0011_update_event_prices'),
    ]

    operations = [
    ]
