# Generated by Django 5.2 on 2025-06-10 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dance_styles', '0012_merge_20250605_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='dancestyle',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='dance_videos/'),
        ),
    ]
